---
- name: Config app.py
  template:
    src: "templates/app.py.j2"
    dest: "{{ dest_dir }}/src/app.py"

# - name: Enable firewalld
#   service:
#     name: firewalld
#     state: started
#     enabled: true

# - name: Open app port
#   firewalld:
#     zone: public
#     port: '{{ app_port }}/tcp'
#     permanent: true
#     state: enabled

# - name: Reload firewalld
#   service:
#     name: firewalld
#     state: reloaded
#     enabled: true